### ISSUE TITLE
Can a single comment be updated? rather than new comments being added each time?

### ISSUE THREAD

**Issue by NullVoxPopuli** [nwtgck/actions-netlify#105]
when doing lots of commits to a WIP/non-draft PR, the number of deploy commen notifications adds up

**Comment by nwtgck** [comment]
Maybe it can. I need to know stateful feature on Actions.

**Comment by lpoulter** [comment]
This feature would be a nice addition. Removing outdated deploy comments from a PR would avoid some confusion.

**Comment by nwtgck** [comment]
@lpoulter Thank you very much for your suggestion and the actual implementation of Danger JS. I'll embed a special comment such as `<!-- NETLIFY DEPLOY COMMENT GENERATED BY ACTIONS_NETLIFY ->` to the markdown comment to search comments.

**Comment by nwtgck** [comment]
I'll solve this in #138

**Comment by nwtgck** [comment]
@NullVoxPopuli @lpoulter Thank you very much!

 I released v1.1.0 for this feature. You can use it with `...@v1.1.0`, `...@v1.1` or `...@v1`.
https://github.com/nwtgck/actions-netlify/blob/5fa3ebacda2ec732937c0c2246e60afcc87cc415/CHANGELOG.md#110---2020-05-10

**Comment by NullVoxPopuli** [comment]
Thanks!
