### ISSUE TITLE
Invalid action input 'enable-github-deployment'

### ISSUE THREAD

**Issue by AlbertXiaoPeng** [nwtgck/actions-netlify#1069]
![image](https://github.com/nwtgck/actions-netlify/assets/44151574/57ac4c34-bfe7-43bb-9567-2ca605e144dc)

**Comment by AlbertXiaoPeng** [comment]
This error is displayed in vscode with the github related plugin installed

**Comment by nwtgck** [comment]
This may be unreleased feature: https://github.com/nwtgck/actions-netlify/issues/1070.

**Comment by AlbertXiaoPeng** [comment]
https://github.com/marketplace/actions/netlify-actions Still show 2.0.0, will update here

**Comment by AlbertXiaoPeng** [comment]
Thank you very much
