### ISSUE TITLE
Update node version to 20

### ISSUE THREAD

**Issue by Talaxy009** [nwtgck/actions-netlify#1150]
Node 16 has reached end-of-life on Sep 2023. GitHub Action also shows this warning: 
![image](https://github.com/nwtgck/actions-netlify/assets/41264828/47a37b9c-1097-4ce0-9915-9c1046292d17)

**Comment by nwtgck** [comment]
Thanks! `nwtgck/actions-netlify@v3.0` using node20 released now.
