### ISSUE TITLE
Support branch deploy

### ISSUE THREAD

**Issue by kwkbtr** [nwtgck/actions-netlify#167]
It seems that there is a draft PR of netlify/js-client to support branch deploy: netlify/js-client#105.
It would be great to have that functionality in actions-netlify too once the above PR is released.

**Comment by nwtgck** [comment]
@kwkbtr Thank you so much for providing the information! I wanted the feature.

**Comment by nwtgck** [comment]
Related(developer note):
- https://open-api.netlify.com/#operation/createSiteDeploy

**Comment by nwtgck** [comment]
Branch deployment is supported in netlify 4.3.0.
#175

**Comment by nwtgck** [comment]
I made a pull request to support branch deploy. Do you know what value should be passed to "branch" in deploy() function?
https://github.com/nwtgck/actions-netlify/pull/176#commitcomment-39622530

**Comment by nwtgck** [comment]
PR: #178

**Comment by nwtgck** [comment]
This feature was released. You can use `@v1`, `@v1.1` or `@v1.1.2`. Usage is here: <https://github.com/nwtgck/actions-netlify/tree/16006c9708ee159d639aff28229210a26b606d16#optional-inputs>

**Comment by kwkbtr** [comment]
Great, thanks!
