### ISSUE TITLE
Release notes would be great 

### ISSUE THREAD

**Issue by screendriver** [nwtgck/actions-netlify#189]
Would it be possible to write a small release note on every release? For example the [latest release](https://github.com/nwtgck/actions-netlify/releases/tag/v1.1.3) does not mention anything. So I had to look into the commit history to see that we now have a new `production-deploy` input (which is great by the way!)

**Comment by nwtgck** [comment]
@screendriver Thanks.

Currently, I managed the release note on Git as CHANGELOG.md. It may better to find a way to generate release note from the CHANGELOG automatically.
(see: <https://github.com/nwtgck/actions-netlify/blob/develop/CHANGELOG.md>)

**Comment by screendriver** [comment]
Cool. Unfortunately GitHub doesn't show this in the releases. So bots like [Renovate](https://renovate.whitesourcesoftware.com/) doesn't show anything when it creates a pull request. 

So shall we close this issue? Or do you want to leave it open?

**Comment by nwtgck** [comment]
@screendriver Good news! I created GitHub releases.

I made a simple tool to update GitHub releases automatically with existing CHANGELOG.md.
https://github.com/nwtgck/changelog-to-gh-release

**Comment by screendriver** [comment]
🎉
