### ISSUE TITLE
Report URL via commit status instead of via comment

### ISSUE THREAD

**Issue by jennybc** [nwtgck/actions-netlify#262]
Thanks very much for this Action. I'm using it successfully for Netlify deploys.

In other workflows (in the lower case sense, not GHA sense), we surface the Netlify deploy URL via a commit status, which is really nice.

https://docs.netlify.com/site-deploys/notifications/#github-commit-statuses

<img width="1188" alt="Screen Shot 2020-08-20 at 9 44 47 AM" src="https://user-images.githubusercontent.com/599454/90800681-d353a680-e2c9-11ea-92ee-df2dd667ddbb.png">

(I guess that image shows using the "git commit checks" idea, but it's pretty similar to how "git commit status" approach looks and works.)

I like that this doesn't have notification consequences and doesn't clutter the PR conversation with its own comment.

Would you consider reporting the URL in that manner as an alternative to the current comment approach?

I am achieving this now by using your action and feeding its output into another action (I still have the comment turned on but I'll probably turn that off soon):

https://github.com/hadley/r-pkgs/blob/6c8e1e2ee1742384a64e707e595f0043fafc927d/.github/workflows/build-book.yaml#L79-L109

The action I'm using to add a status update to a commit is [Sibz/github-status-action](https://github.com/Sibz/github-status-action).

You can see all of this working together in this PR:

https://github.com/hadley/r-pkgs/pull/648/commits

**Comment by nwtgck** [comment]
@jennybc Thank you very much for your suggestion! I like the suggestion using GitHub Status.

<https://github.com/Sibz/github-status-action> will be very helpful to implement this feature in this Action.

<img width="500" alt="image" src="https://user-images.githubusercontent.com/10933561/90835731-520f1900-e388-11ea-8ab3-437030d55c2f.png">
found in https://github.com/hadley/r-pkgs/pull/648

**Comment by nwtgck** [comment]
I implemented this feature. I'll release it soon.

<img width="439" alt="image" src="https://user-images.githubusercontent.com/10933561/90836725-1de92780-e38b-11ea-91a8-90b18bb4306c.png">

https://github.com/nwtgck/piping-ui-web/tree/1df5b7596f16f31b0fe2ecd70f0f64dd8124684c

**Comment by nwtgck** [comment]
@jennybc I released <https://github.com/nwtgck/actions-netlify/releases/tag/v1.1.8> with GitHub commit status! You can use in `@v1.1.8`, `@v1.1` and `@v1`.

**Comment by jennybc** [comment]
Thanks for being so receptive. I look forward to trying out the new release!
