### ISSUE TITLE
##[error]ENOENT: no such file or directory, lstat '/home/runner/work/example.com/example.com/dist'

### ISSUE THREAD

**Issue by kaihendry** [nwtgck/actions-netlify#27]
What am I missing here? https://github.com/kaihendry/dabase.com/pull/1/checks?check_run_id=461522842

Hugo by default uses **public** for _publish-dir_ so shouldn't it be using that?

Thank you!

**Comment by nwtgck** [comment]
@kaihendry Hi,

I  think your workflow file is https://github.com/kaihendry/dabase.com/blob/82847a629e5073b050846af367313d9200094e64/.github/workflows/netlify.yml.

In the workfowlo file, I think the "checkout" is missing. After checkout, you can build by some tool in your case Hugo, and you also change the 'publish-dir' to "public".

**Comment by nwtgck** [comment]
@kaihendry I think I can solve the issue on this pull request on your repository: https://github.com/kaihendry/dabase.com/pull/2. Please check it.

I'd like to disscuss the PR on your repository. Thanks.
