### ISSUE TITLE
Don't generate /dist/typescript

### ISSUE THREAD

**Issue by nwtgck** [nwtgck/actions-netlify#28]
## Problem

Currently `dist/typescript` is automatically generated by `npm run all`. I don't want to generate it because it causes type-definition's conflict problem when you run `npm run build` again without `rm -r ./dist`.

**Comment by peaceiris** [comment]
We do not need run `tsc` before `ncc build`.

**Comment by nwtgck** [comment]
@peaceiris 

Thanks!

I ran as follows, but "./dist/typescript" was generated.

```bash
rm -r dist
# NOTE: I don't run "npm run build" not to run `tsc`
npm run format && npm run lint && npm run pack && npm test
```

**Comment by peaceiris** [comment]
How about `ncc build ./src/main.ts -o dist`?

**Comment by nwtgck** [comment]
Thanks! But still generated.

<img width="413" alt="image" src="https://user-images.githubusercontent.com/10933561/75086731-d1a76100-557a-11ea-8b28-5f6ef8a81385.png">

**Comment by nwtgck** [comment]
## note for me

Here are the total differences between the template and current files.
<https://github.com/nwtgck/actions-netlify/compare/0340e0293fdb474ace27d904e11a507d435e4600...825cfcaaeb3736f5a1b1b14608388c213a229b71>
I seems there is no difference related to some configurations.

**Comment by South-Paw** [comment]
Somehow it's related to the `netlify` import... might be something to do with how they export it 🤔

Removing the `netlify` import and then running `ncc` for me;

![image](https://user-images.githubusercontent.com/2154764/75740928-e56a7880-5d6d-11ea-9c35-6a013b9e018f.png)

If I bring back the netlify import, it builds `dist/typescript` again.

**Comment by nwtgck** [comment]
@South-Paw Thank you very much for the information! According your investigation, `import NetlifyAPI from 'netlify'` creates /dist/typescript.

**Comment by South-Paw** [comment]
@nwtgck 👍 

It might be because of how they build/distribute their package... might be best to raise and issue over [there](https://github.com/netlify/js-client) to see if you can get anywhere.

**Comment by nwtgck** [comment]
@South-Paw Thanks. Maybe I should post the issue. But, netlify/js-client doesn't use TypeScript at all, written in JavaScript. I'd like to investigate the reason more.

**Comment by South-Paw** [comment]
@nwtgck even though they don't use Typescript, they compile their package to a CJS format using webpack/babel.

I suspect that this isn't playing nice with `ncc` somehow but even so I would say it is certainly their packages issue.

I have another [Github action]() that I also checked how it built and I don't get the weird `dist/typescript` folder when I build using `ncc` either

**Comment by nwtgck** [comment]
@South-Paw  Thanks.
> I'm not very well versed in package formats (CJS/UMD etc)
Me too.

Your are the finder of `import "netlify"` thing. I think it is better to create the issue by you because you can be a contributor!

**Comment by nwtgck** [comment]
#178 solves this issue! Thanks @rajington!
