### ISSUE TITLE
PR open which isn't a member of the repo gets ##[error]Missing access token

### ISSUE THREAD

**Issue by kaihendry** [nwtgck/actions-netlify#32]
![image](https://user-images.githubusercontent.com/765871/75409702-74355a80-5954-11ea-819a-a0921834f535.png)

https://github.com/kaihendry/dabase.com/runs/471466202 is the same as https://github.com/kaihendry/dabase.com/pull/2#issuecomment-589909000

I'm not sure how to address this.

**Comment by nwtgck** [comment]
@kaihendry Hello again.

The action is triggered by `@cheeaun`. I guess someone who is not a maintainer can not use the secrets. [As you said before](https://github.com/kaihendry/dabase.com/pull/2#issuecomment-589909620), it may be permission problem.

The latest deployment to Netlify was successful on master branch triggered by you.
<img width="932" alt="image" src="https://user-images.githubusercontent.com/10933561/75412548-2a557000-5966-11ea-95f6-d01dd150ec4b.png">

**Comment by nwtgck** [comment]
I found official description about the secret on GitHub.
<img width="744" alt="image" src="https://user-images.githubusercontent.com/10933561/75412816-08a8b880-5967-11ea-843d-2786e812efe7.png">

> Secrets are not passed to workflows that are triggered by a pull request from a fork.

**Comment by kaihendry** [comment]
hhhmmmm... so this makes this action kindof useless for external contributions then?

Or do you think we can get around the secrets limitation?

**Comment by nwtgck** [comment]
> hhhmmmm... so this makes this action kindof useless for external contributions then?
I think so too...

Unfortunately, I have no workaround.

**Comment by kaihendry** [comment]
I posted on https://github.community/t5/GitHub-Actions/Secrets-for-PRs-who-are-not-collaborators/td-p/47900

I mean maybe it's kindof dangerous to have Netlify publish a site ... struggling to weigh up the risks, since the PR is on Github to begin with.

**Comment by nwtgck** [comment]
Very great! I want to keep watching the post.

**Comment by nwtgck** [comment]
This issue seems to be a general issue of GitHub Actions. So I close this.
