### ISSUE TITLE
Netlify credentials not provided, not deployable

### ISSUE THREAD

**Issue by gee1k** [nwtgck/actions-netlify#361]
![image](https://user-images.githubusercontent.com/12059800/99866431-133d6900-2bec-11eb-871c-1941f8f03b88.png)

![image](https://user-images.githubusercontent.com/12059800/99866448-2d774700-2bec-11eb-8ac6-2d809239dc02.png)

![image](https://user-images.githubusercontent.com/12059800/99866442-23eddf00-2bec-11eb-99d6-23d18a13f843.png)

**Comment by pranshuchittora** [comment]
Getting the same error

**Comment by nwtgck** [comment]
@pranshuchittora
 Have you set the secrets?

**Comment by pranshuchittora** [comment]
Yes

**Comment by pranshuchittora** [comment]
I tried everything, didn't worked. Therefore changed the approach (workaround to avoid this)

**Comment by nwtgck** [comment]
@pranshuchittora Are you using actions-netlify on a forked repo?

**Comment by nwtgck** [comment]
In some setting, PR from a forked repo does not provide the secrets.
