### ISSUE TITLE
Support for multiple deploys on the same PR?

### ISSUE THREAD

**Issue by NullVoxPopuli** [nwtgck/actions-netlify#384]
the overwrite comment on PR uses a static lookup string. should it instead be based on the app id? This would allow to reuse the same comment with multiple deploys?

**Comment by peaceiris** [comment]
I have opened my pull-request #482 for this. Welcome your feedback!

**Comment by peaceiris** [comment]
I realized that the pull-request is not related to here. Sorry.

**Comment by kaisermann** [comment]
I'm also in need of support for multiple deploy messages. I'm happy to open a PR for it, but I would like to know if 1) this is desired 2) what can be used as an id (thought about `alias` but its optional)
