### ISSUE TITLE
Set the deploy URL to outputs for this action

### ISSUE THREAD

**Issue by kentaro-m** [nwtgck/actions-netlify#46]
Hi, @nwtgck.

I want to use `deploy_ssl_url` and `ssl_url` in the other actions (e.g. send a message to a Slack channel), so I want to add it to `outputs` for this action.

I will create a pull request if you accept this enhancement.

An example of implementation: https://github.com/kentaro-m/actions-netlify/commit/61f6a010e0ee71a3f4183b15168250be5c93a38b

**Comment by nwtgck** [comment]
@kentaro-m Thank you very much! I will accept it.
