### ISSUE TITLE
Error: Request path contains unescaped characters

### ISSUE THREAD

**Issue by KnorpelSenf** [nwtgck/actions-netlify#689]
I keep on running into the same issue and the error message is not helpful. All I get is this:
```bash
Run nwtgck/actions-netlify@v1.2
  with:
    publish-dir: ./bundling/bundles
    production-branch: main
    netlify-config-path: ./bundling/bundles/netlify.toml
  env:
    NETLIFY_SITE_ID: ***
    NETLIFY_AUTH_TOKEN: ***
Error: Request path contains unescaped characters
```
How can I investigate what the problem is?

FYI there are no weird characters in the publish directoy:
```
Run find bundling
bundling
bundling/.gitignore
bundling/bundle-es6.ts
bundling/bundles
bundling/bundles/es6-dev.js
bundling/bundles/es6-v1.4.2.js
bundling/bundles/netlify.toml
bundling/netlify.toml
```

**Comment by nwtgck** [comment]
Thanks for the report. I'll see https://github.com/grammyjs/grammY/pull/111

**Comment by nwtgck** [comment]
@KnorpelSenf I posted a comment on grammyjs/grammY#111.

**Comment by nwtgck** [comment]
Notes: Where the error message come from (root):

* Node.js: https://github.com/nodejs/node/blob/1e8b296c58b77d3b7b46d45c7ef3e44981c5c3e7/lib/internal/errors.js#L1561
* test: https://github.com/nodejs/node/blob/e46c680bf2b211bbd52cf959ca17ee98c7f657f5/test/parallel/test-http-invalid-path-chars.js#L17
* test: https://github.com/nodejs/node/blob/e46c680bf2b211bbd52cf959ca17ee98c7f657f5/test/parallel/test-http-client-unescaped-path.js#L34

**Comment by KnorpelSenf** [comment]
It would be very helpful to know what operation is attempted when the unescaped characters are found. Even better would be to print the path with the unescaped characters to stdout.

Is it a file path? Is it the path in a URL? Which file or URL would that be?

Is there any way to print more logs so we can see what's going on?

**Comment by KnorpelSenf** [comment]
The credentials are used in query parameters. The issue was some accidental whitespace in the `NETLIFY_SITE_ID` secret. Given that authentication credentials are part of the URL, it makes sense not to log them publicly. @nwtgck thank you for your help!
