### ISSUE TITLE
How to delete deploy preview on PR merge?

### ISSUE THREAD

**Issue by leecalcote** [nwtgck/actions-netlify#752]
We would like to clean up our old deploy previews by deleting them after the respective PR has merged. Does this action facilitate for this?

**Comment by nwtgck** [comment]
No. This action does not facilitate for that. 

I'm not sure Netlify provides deletion. One idea to solve the probleam is overwriting the previews.

**Comment by noelforte** [comment]
@leecalcote it's not possible to delete deploy previews because of how Netlify's CDN setup works, see this answer (https://answers.netlify.com/t/does-each-deploy-preview-stay-available-forever/12601?page=3) as well as the other replies on that thread for additional context.

**Comment by leecalcote** [comment]
Thank you, gents. This answers my question. Much appreciated.
