### ISSUE TITLE
(More) deprecation warning for Node 12

### ISSUE THREAD

**Issue by jennybc** [nwtgck/actions-netlify#874]
I'm still seeing this:

```
Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
Please update the following actions to use Node.js 16: nwtgck/actions-netlify@v1.2
```

After a previous issue about this was closed, someone posted another possible place this needs to be resolved, FWIW.

https://github.com/nwtgck/actions-netlify/issues/837#issuecomment-1307407424

**Comment by nwtgck** [comment]
Thanks. This will be fixed by https://github.com/nwtgck/actions-netlify/pull/847 or I will commit without that PR after several tests.

**Comment by nwtgck** [comment]
https://github.com/nwtgck/actions-netlify/pull/847 merged
