### ISSUE TITLE
Promise timed out after 1200000 milliseconds

### ISSUE THREAD

**Issue by ndarilek** [nwtgck/actions-netlify#95]
Getting the error:

Promise timed out after 1200000 milliseconds

with v1.0.12. Here is my configuration:

```
    - uses: nwtgck/actions-netlify@v1.0.12
      with:
        publish-dir: exports/html5
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
```

Here are my logs, though they're not entirely helpful:

```
2020-04-17T17:23:52.3852101Z ##[group]Run nwtgck/actions-netlify@v1.0.12
2020-04-17T17:23:52.3852244Z with:
2020-04-17T17:23:52.3852363Z   publish-dir: exports/html5
2020-04-17T17:23:52.3852472Z env:
2020-04-17T17:23:52.3853290Z   NETLIFY_AUTH_TOKEN: ***
2020-04-17T17:23:52.3853418Z   NETLIFY_SITE_ID: ***
2020-04-17T17:23:52.3853529Z ##[endgroup]
2020-04-17T17:43:52.9631918Z ##[error]Promise timed out after 1200000 milliseconds
```

Thanks.

**Comment by nwtgck** [comment]
@ndarilek Thank you very much for reporting.

I'm not sure the cause. I use this action (actions-netlify) in some projects without failures.

**Comment by ndarilek** [comment]
How do we get more information? I'm surprised there isn't a stacktrace. 
Not very familiar with GitHub Actions--I'm just migrating several 
projects to them so am new.

**Comment by ndarilek** [comment]
OK, figured it out. I'm uploading game engine assets created by another action, the action zips them up, and I hadn't correctly unarchived the zip into the directory I was deploying. So the action was trying to deploy a directory with a single zip archive, and Netlify didn't like that. FWIW, netlify-cli bombed on this too. Things work well now that I've fixed my process.

Thanks for this action!
